import { expect, test } from '@playwright/test'

test.setTimeout(180000)
test.use({ actionTimeout: 15000 })
test.beforeEach(async ({ context }) => {
  await context.route('**/__index__', route => route.fulfill({ body: '<p>Preview</p>' }))
})

test('a delayed project action cannot overwrite the selected theme on restart', async ({ page, context }) => {
  await page.goto('/tests/browser/workbench.html?files&persist-theme&delay-directory')
  await expect(page.getByRole('button', { name: 'Projects', exact: true })).toBeVisible({ timeout: 120000 })
  await page.getByRole('button', { name: 'Projects', exact: true }).click()
  await page.locator('.workspace-project').click()
  await expect.poll(() => page.evaluate(() => (window as any).__workbench.calls.some((c: any) => c.cmd === 'plugin:dialog|open'))).toBe(true)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.locator('[data-theme-option="gallery-nord"]').click()
  await expect.poll(() => page.evaluate(() => (window as any).__workbench.getConfig().theme)).toBe('gallery-nord')
  await page.evaluate(() => (window as any).__workbench.finishDirectory('C:\\Projects\\website'))
  await expect.poll(() => page.evaluate(() => (window as any).__workbench.getConfig().cwd)).toBe('C:\\Projects\\website')
  expect(await page.evaluate(() => (window as any).__workbench.getConfig().theme)).toBe('gallery-nord')
  await page.close()
  const reopened = await context.newPage()
  await reopened.goto('/tests/browser/workbench.html?files&persist-theme')
  await expect(reopened.locator('html')).toHaveAttribute('data-theme', 'gallery-nord')
  await reopened.getByRole('button', { name: 'Settings', exact: true }).click()
  await expect(reopened.locator('[data-theme-option="gallery-nord"]')).toHaveAttribute('aria-pressed', 'true')
})

test('failed saves remain visible in Settings and retry writes the latest theme', async ({ page }) => {
  await page.goto('/tests/browser/workbench.html?files&persist-theme')
  await expect(page.getByRole('button', { name: 'Settings', exact: true })).toBeVisible({ timeout: 120000 })
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.evaluate(() => (window as any).__workbench.failConfigSaves(true))
  await page.locator('[data-theme-option="gallery-ayu"]').click()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('Settings could not be saved')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'gallery-ayu')
  await page.evaluate(() => (window as any).__workbench.failConfigSaves(false))
  await page.getByRole('button', { name: 'Retry saving', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect.poll(() => page.evaluate(() => (window as any).__workbench.getConfig().theme)).toBe('gallery-ayu')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'gallery-ayu')
})
