import { expect, test } from '@playwright/test'
import { resolve } from 'node:path'

test.setTimeout(180000)
test.use({ deviceScaleFactor: 1 })
const themeFile = resolve('community-themes/monokai-pro-ce/monokai-pro-ce.json')

test('imports CE locally, themes editor and terminal, survives reload and can be removed', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 2048, height: 1280 })
  await page.route('**/__index__', route => route.fulfill({ contentType: 'text/html', body: '<p>Preview</p>' }))
  await page.goto('/tests/browser/workbench.html?files&persist-theme')
  await expect(page.getByRole('button', { name: 'Code', exact: true })).toBeVisible({ timeout: 120000 })
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await page.locator('[data-file-entry="scripts"]').click()
  await page.locator('[data-file-entry="train.py"]').click()
  const editor = page.locator('[data-workspace-view="files"] .cm-editor')
  await editor.locator('.cm-content').click()
  await page.keyboard.press('Control+End')
  await page.keyboard.type('\n# next: compare the baseline against seed 43')
  await page.getByRole('button', { name: 'Show terminal in Files', exact: true }).click()
  const terminal = page.locator('#workspace-terminal [data-terminal-kind="shell"]')
  await expect(terminal.locator('.xterm')).toBeVisible()
  const starts = await page.evaluate(() => (window as any).__workbench.calls.filter((c: any) => c.cmd === 'term_start').length)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await expect(page.getByRole('button', { name: /Monokai Pro/ })).toHaveCount(0)
  await page.locator('input[type="file"]').setInputFiles(themeFile)
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'imported:monokai-pro-ce')
  await expect(page.getByRole('button', { name: /Monokai Pro \(CE\).*Active/ })).toHaveAttribute('aria-pressed', 'true')
  await page.locator('.settings-sidebar').getByRole('button').first().click()
  await expect(editor).toHaveCSS('background-color', 'rgb(45, 42, 46)')
  await expect(terminal).toHaveCSS('background-color', 'rgb(45, 42, 46)')
  await expect(editor.locator('.cm-content')).toContainText('seed 43')
  await expect(editor.locator('.cm-line span').filter({ hasText: /^from$/ }).first()).toHaveCSS('color', 'rgb(255, 97, 136)')
  expect(await page.evaluate(() => (window as any).__workbench.calls.filter((c: any) => c.cmd === 'term_start').length)).toBe(starts)
  expect(await page.evaluate(() => (window as any).__workbench.calls.filter((c: any) => c.cmd === 'term_kill').length)).toBe(0)
  await page.screenshot({ path: 'community-themes/monokai-pro-ce/screenshot.png' })

  // Separate window load: native config fixture and local palette both survive.
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'imported:monokai-pro-ce')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.locator('input[type="file"]').setInputFiles(themeFile)
  await expect(page.getByRole('alert')).toContainText('already imported')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'imported:monokai-pro-ce')
  await page.locator('input[type="file"]').setInputFiles({ name: 'unsafe.json', mimeType: 'application/json', buffer: Buffer.from('{"theme":{"vars":{"canvas":"url(https://example.com)"}}}') })
  await expect(page.getByRole('alert')).toContainText('not a valid Linco theme')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'imported:monokai-pro-ce')
  await page.getByRole('button', { name: 'Remove local copy of Monokai Pro (CE)', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'linco-light')
  await expect(page.getByRole('button', { name: /Monokai Pro/ })).toHaveCount(0)
  await page.locator('input[type="file"]').setInputFiles(themeFile)
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'imported:monokai-pro-ce')
  expect(errors).toEqual([])
})
