import { expect, test, type Page } from '@playwright/test'

const reviewButton = (page: Page) => page.getByRole('button', { name: /Review this file now/ })
const saved = (page: Page) => page.getByRole('status').getByText('Review history saved on this device', { exact: true })
const history = (page: Page) => page.getByRole('region', { name: 'Review history' })
const calls = (page: Page) => page.evaluate(() => (window as unknown as { writingCalls(): number }).writingCalls())

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('linco.locale', 'en'))
  await page.goto('/tests/browser/latex-memory.html')
  await expect(page.getByText('Review on request', { exact: false })).toBeVisible()
})

test('restores pending suggestions and decisions after reload without an AI call', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  expect(await calls(page)).toBe(0)
  await reviewButton(page).click()
  await expect(saved(page)).toBeVisible()
  await page.getByRole('button', { name: 'Review history', exact: true }).click()
  await expect(history(page).locator('article')).toHaveCount(2)
  await page.screenshot({ path: 'artifacts/writing-memory-preview.png' })
  await history(page).locator('article').first().getByRole('button', { name: 'Accept' }).click()
  await expect(history(page).locator('article')).toHaveCount(1)
  await history(page).locator('article').first().getByRole('button', { name: 'Reject' }).click()
  await expect(saved(page)).toBeVisible()
  await page.reload()
  await expect(saved(page)).toBeVisible()
  expect(await calls(page)).toBe(0)
  await page.getByRole('button', { name: 'Review history', exact: true }).click()
  await expect(history(page).locator('article')).toHaveCount(0)
  await expect(history(page).getByText(/Suggestion accepted/)).toBeVisible()
  await expect(history(page).getByText(/Suggestion dismissed/)).toBeVisible()
  await expect(page.locator('.cm-content')).toContainText('We are testing')
  const download = page.waitForEvent('download')
  await history(page).getByRole('button', { name: 'Export JSON' }).click()
  expect((await download).suggestedFilename()).toBe('linco-writing-history.json')
  expect(errors).toEqual([])
})

test('pending findings restore; changed source and another host do not reuse old findings', async ({ page }) => {
  await reviewButton(page).click()
  await expect(saved(page)).toBeVisible()
  await page.reload()
  await expect(saved(page)).toBeVisible()
  await page.getByRole('button', { name: 'Review history', exact: true }).click()
  await expect(history(page).locator('article')).toHaveCount(2)
  expect(await calls(page)).toBe(0)
  await history(page).getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Toggle paper' }).click()
  await page.getByRole('button', { name: 'External edit' }).click()
  await page.getByRole('button', { name: 'Toggle paper' }).click()
  await expect(saved(page)).toBeVisible()
  await page.getByRole('button', { name: 'Review history', exact: true }).click()
  await expect(history(page).locator('article')).toHaveCount(0)
  await expect(history(page).getByText(/Earlier source versions/)).toBeVisible()
  await history(page).getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Switch host' }).click()
  await expect(page.getByText('Review on request', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Review history', exact: true }).click()
  await expect(history(page).locator('details')).toHaveCount(0)
  expect(await calls(page)).toBe(0)
})

test('a second window cannot overwrite another window’s saved history', async ({ page, context }) => {
  const other = await context.newPage()
  await other.goto('/tests/browser/latex-memory.html')
  await expect(other.getByText('Review on request', { exact: false })).toBeVisible()
  await reviewButton(page).click()
  await expect(saved(page)).toBeVisible()
  await reviewButton(other).click()
  await expect(other.getByRole('status')).toContainText('Review history not saved')
  await expect(other.getByRole('status')).toContainText('changed in another window')
  await page.reload()
  await expect(saved(page)).toBeVisible()
  await page.getByRole('button', { name: 'Review history', exact: true }).click()
  await expect(history(page).locator('details')).toHaveCount(1)
  expect(await calls(page)).toBe(0)
})

test('changed research evidence retires active findings but preserves their cited excerpts', async ({ page }) => {
  await page.getByRole('button', { name: 'Change research evidence' }).click()
  await reviewButton(page).click()
  await expect(saved(page)).toBeVisible()
  await page.getByRole('button', { name: 'Review history', exact: true }).click()
  await expect(history(page).locator('article')).toHaveCount(2)
  const before = await calls(page)
  await page.getByRole('button', { name: 'Change research evidence' }).click()
  await expect(history(page).locator('article')).toHaveCount(0)
  const checkpoint = history(page).locator('details').first()
  await checkpoint.locator(':scope > summary').click()
  await expect(checkpoint).toContainText('Earlier manuscript or research context')
  const source = checkpoint.locator('details').first()
  await source.locator('summary').click()
  await expect(source).toContainText('Synthetic captured evidence for this review.')
  expect(await calls(page)).toBe(before)
})
