import { expect, test, type Page } from '@playwright/test'

const pageUrl = 'https://www.notion.so/0123456789abcdef0123456789abcdef'
const calls = (page: Page, cmd: string) => page.evaluate((name) => (window as any).__workbench.calls.filter((c: any) => c.cmd === name), cmd)
const visible = async (page: Page) => (await calls(page, 'notion_layout')).at(-1)?.args.visible
async function open(page: Page, query = '') {
  await page.goto(`/tests/browser/workbench.html${query}`)
  await page.getByRole('button', { name: 'Notes', exact: true }).click()
}

test('native Notes is lazy, fits beside the agent, and hides for modes and overlays', async ({ page }) => {
  await page.goto('/tests/browser/workbench.html')
  await expect(page.getByRole('button', { name: 'Notes', exact: true })).toBeVisible()
  expect(await calls(page, 'notion_open')).toHaveLength(0)
  await page.getByRole('button', { name: 'Notes', exact: true }).click()
  await expect.poll(() => visible(page)).toBe(true)
  const layout = (await calls(page, 'notion_layout')).at(-1).args.bounds
  const agent = await page.locator('.pane-composer').boundingBox()
  expect(layout.x).toBeGreaterThanOrEqual(agent!.x + agent!.width)
  expect(layout.height).toBeGreaterThan(500)
  await expect(page.locator('[data-workspace-view="notion"] iframe')).toHaveCount(0)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await expect.poll(() => visible(page)).toBe(false)
  await page.locator('.settings-sidebar').getByRole('button').first().click()
  await expect.poll(() => visible(page)).toBe(true)
  await page.getByRole('button', { name: 'Projects', exact: true }).click()
  await expect.poll(() => visible(page)).toBe(false)
  await page.getByRole('button', { name: 'Close projects', exact: true }).click()
  await expect.poll(() => visible(page)).toBe(true)
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await expect.poll(() => visible(page)).toBe(false)
  const count = (await calls(page, 'notion_open')).length
  await page.getByRole('button', { name: 'Vibe Working', exact: true }).click()
  await expect.poll(() => visible(page)).toBe(true)
  expect(await calls(page, 'notion_open')).toHaveLength(count)
  await page.setViewportSize({ width: 900, height: 600 })
  await expect.poll(async () => (await calls(page, 'notion_layout')).at(-1).args.bounds.height).toBeLessThan(520)
})

test('links a project persistently and shares canonical read-only context only after confirmation', async ({ page }) => {
  await open(page)
  await expect(page.getByRole('button', { name: 'Use in agent', exact: true })).toBeDisabled()
  await page.getByRole('textbox', { name: 'Notion page URL' }).fill(`${pageUrl}?token=private`)
  await page.getByRole('textbox', { name: 'Notion page URL' }).press('Enter')
  await expect(page.getByRole('button', { name: 'Link this page to the project' })).toBeEnabled()
  await page.getByRole('button', { name: 'Link this page to the project' }).click()
  await expect(page.getByText('Project notebook linked', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Notes', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Notion page URL' })).toHaveValue(pageUrl)
  await page.getByRole('button', { name: 'Use in agent', exact: true }).click()
  await expect.poll(() => visible(page)).toBe(false)
  expect((await calls(page, 'term_write')).some((c: any) => c.args.data.includes(pageUrl))).toBe(false)
  await page.getByRole('button', { name: 'Read with agent', exact: true }).click()
  await expect.poll(async () => (await calls(page, 'term_write')).some((c: any) => c.args.data.includes('Do not change the note yet'))).toBe(true)
  expect((await calls(page, 'term_write')).some((c: any) => c.args.data.includes('token=private'))).toBe(false)
})

test('rejects unsafe links and explains MCP separately without executing setup', async ({ page }) => {
  await open(page)
  const initial = (await calls(page, 'notion_open')).length
  await page.getByRole('textbox', { name: 'Notion page URL' }).fill('https://notion.so.evil.test/')
  await page.getByRole('textbox', { name: 'Notion page URL' }).press('Enter')
  await expect(page.getByRole('alert')).toContainText('Enter an HTTPS link')
  expect(await calls(page, 'notion_open')).toHaveLength(initial)
  await page.getByRole('button', { name: 'Connect Codex', exact: true }).click()
  await expect.poll(() => visible(page)).toBe(false)
  await expect(page.getByRole('heading', { name: 'One notebook. You and Codex.' })).toBeVisible()
  expect((await calls(page, 'term_write')).some((c: any) => c.args.data.includes('mcp add'))).toBe(false)
  await page.getByRole('button', { name: 'Back to the notebook' }).click()
  await expect.poll(() => visible(page)).toBe(true)
})

test('notes can open before choosing a coding project; native failures are recoverable', async ({ page }) => {
  await open(page, '?empty&notion-error')
  await expect(page.getByRole('alert')).toContainText('Native browser unavailable')
  await expect(page.getByRole('heading', { name: 'Open a project' })).toBeHidden()
  await expect(page.getByRole('button', { name: 'Use in agent', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Native browser unavailable')
})

test('sets up an editable notebook and creates a template record without asking the agent', async ({ page }) => {
  await open(page)
  await expect(page.getByRole('button', { name: 'Local · connected', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Templates', exact: true }).click()
  await expect.poll(() => visible(page)).toBe(false)
  await expect(page.getByRole('dialog')).toContainText('Your project notebook')
  expect(await calls(page, 'notion_tool')).toHaveLength(0)
  await page.getByRole('button', { name: 'Create project notebook', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Start a new note' })).toBeVisible()
  await page.getByRole('button', { name: 'Experiment A reproducible test' }).click()
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('Linco revision · first trial')
  await page.getByRole('textbox', { name: 'Starting note · optional', exact: true }).fill('Test whether progress and feedback are easier to follow.')
  await page.screenshot({ path: 'artifacts/notion-template-picker.png' })
  await page.getByRole('button', { name: 'Create in Notion', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect.poll(() => visible(page)).toBe(true)
  const writes = (await calls(page, 'notion_tool')).filter((call: any) => call.args.tool === 'notion-create-pages')
  const record = writes.at(-1).args.arguments
  expect(record.pages[0].properties.Status).toBe('Draft')
  expect(record.pages[0].content).toContain('Test whether progress')
  expect(record.pages[0].content).toContain('## Run log')
  expect((await calls(page, 'term_write')).some((call: any) => call.args.data.includes('first trial'))).toBe(false)
  await page.getByRole('button', { name: 'Use in agent', exact: true }).click()
  await page.getByRole('textbox', { name: 'Your feedback or question · optional' }).fill('Please review the acceptance criteria.')
  await page.getByRole('button', { name: 'Read with agent', exact: true }).click()
  await expect.poll(async () => (await calls(page, 'term_write')).some((call: any) => call.args.data.includes('Please review the acceptance criteria.'))).toBe(true)
  expect((await calls(page, 'term_write')).some((call: any) => call.args.data.includes('## Run log'))).toBe(true)
})

test('template picker stays compact at small sizes and adapts to dark mode', async ({ page }) => {
  await open(page, '?theme=linco-dark')
  await expect(page.locator('html')).toHaveAttribute('data-theme-dark', '1')
  await page.getByRole('button', { name: 'Templates', exact: true }).click()
  await page.getByRole('button', { name: 'Create project notebook', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Start a new note' })).toBeVisible()
  await page.setViewportSize({ width: 900, height: 600 })
  const bounds = await page.getByRole('dialog').boundingBox()
  expect(bounds!.y).toBeGreaterThanOrEqual(0)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(600)
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('A compact notebook')
  await expect(page.getByRole('button', { name: 'Create in Notion', exact: true })).toBeInViewport()
  await page.screenshot({ path: 'artifacts/notion-template-picker-dark.png' })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect.poll(() => visible(page)).toBe(true)
})

test('disconnected notebook actions do not create content or start authorization automatically', async ({ page }) => {
  await open(page, '?notion-disconnected')
  await page.getByRole('button', { name: 'Templates', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Connect Notion on this computer')
  await expect(page.getByRole('button', { name: 'Create project notebook', exact: true })).toHaveCount(0)
  expect(await calls(page, 'notion_tool')).toHaveLength(0)
})

test('an uncertain creation keeps the draft visible and is never retried automatically', async ({ page }) => {
  await open(page, '?notion-write-error')
  await page.getByRole('button', { name: 'Templates', exact: true }).click()
  await page.getByRole('button', { name: 'Create project notebook', exact: true }).click()
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('Keep this draft')
  await page.getByRole('button', { name: 'Create in Notion', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Check Notion before retrying')
  await expect(page.getByRole('textbox', { name: 'Title', exact: true })).toHaveValue('Keep this draft')
  const recordCalls = (await calls(page, 'notion_tool')).filter((call: any) => call.args.arguments.parent?.data_source_id)
  expect(recordCalls).toHaveLength(1)
})

test('an older desktop backend is identified as an app update, not failed OAuth', async ({ page }) => {
  await open(page, '?notion-old-backend')
  await expect(page.getByRole('button', { name: 'Desktop update needed', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Templates', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Rebuild and restart Linco')
  await expect(page.getByRole('dialog')).toContainText('signing in again will not update the app')
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Connect Codex', exact: true })).toHaveCount(0)
})
