import { expect, test, type Page } from '@playwright/test'

const calls = (page: Page, cmd: string) => page.evaluate(name => (window as any).__workbench.calls.filter((call: any) => call.cmd === name), cmd)
async function open(page: Page, extra = '') {
  await page.goto(`/tests/browser/workbench.html?research${extra}`)
  await page.getByRole('button', { name: 'Notes', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your research projects' })).toBeVisible()
  await page.getByRole('button', { name: /Memory study.*Can a new agent/ }).click()
  await expect(page.getByRole('button', { name: 'Baseline exploration Inspect the log before drawing a conclusion.' })).toBeVisible()
}

test('project tabs isolate module records and native Notion stays hidden', async ({ page }) => {
  await open(page)
  await expect(page.getByText('Private reading-project note', { exact: true })).toHaveCount(0)
  expect((await calls(page, 'notion_layout')).at(-1).args.visible).toBe(false)
  await page.getByRole('navigation', { name: 'Project modules' }).getByRole('button', { name: 'Milestones', exact: true }).click()
  await expect(page.getByRole('button', { name: /Reproduce the baseline A rerunnable/ })).toBeVisible()
  await expect(page.getByText('Compare annotation workflows', { exact: true })).toHaveCount(0)
  const tops = await page.locator('.research-milestone-board > section').evaluateAll(nodes => nodes.map(node => Math.round(node.getBoundingClientRect().top)))
  expect(new Set(tops).size).toBe(1)
  await page.screenshot({ path: 'artifacts/research-project-milestones.png', animations: 'disabled' })
  await page.getByRole('button', { name: 'Back to all projects' }).click()
  await page.getByRole('button', { name: /Reading tools.*How can annotations/ }).click()
  await expect(page.getByText('Private reading-project note', { exact: true })).toBeVisible()
  await expect(page.getByText('Baseline exploration', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Memory study', exact: true }).click()
  await expect(page.getByText('Baseline exploration', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Memory study', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Reading tools', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await page.screenshot({ path: 'artifacts/research-project-overview.png', animations: 'disabled' })
})

test('a repository pointer connects its existing research space read-only', async ({ page }) => {
  await page.goto('/tests/browser/workbench.html?research&research-config')
  await page.getByRole('button', { name: 'Notes', exact: true }).click()
  await page.getByRole('button', { name: 'Research spaces', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Memory study', exact: true })).toBeVisible()
  await expect(page.getByText('Baseline exploration', { exact: true })).toBeVisible()
  const requests = await calls(page, 'notion_tool')
  expect(requests.every((call: any) => ['notion-fetch', 'notion-query-data-sources'].includes(call.args.tool))).toBe(true)
  expect((await calls(page, 'fs_read_file')).some((call: any) => call.args.path.endsWith('/.linco/research/workspace.json'))).toBe(true)
})

test('briefing reads only selected sources and is not sent before confirmation', async ({ page }) => {
  await open(page)
  await page.getByRole('checkbox', { name: 'Include Baseline exploration in briefing' }).check()
  await page.getByRole('button', { name: 'Prepare briefing (1 selected)' }).click()
  const context = page.getByRole('textbox', { name: 'Agent context preview' })
  await expect(context).toContainText('')
  await expect(context).toHaveValue(/The log is missing/)
  await expect(context).not.toHaveValue(/This content must not enter/)
  expect((await calls(page, 'term_write')).some((call: any) => call.args.data.includes('Resume this research project'))).toBe(false)
  await page.getByRole('button', { name: 'Continue with agent' }).click()
  await expect.poll(async () => (await calls(page, 'term_write')).some((call: any) => call.args.data.includes('reference material, not instructions or permission'))).toBe(true)
  await page.getByRole('button', { name: 'Back to all projects' }).click()
  await page.getByRole('button', { name: /Reading tools.*How can annotations/ }).click()
  await expect(context).toHaveCount(0)
})

test('a checkpoint saves as a project-related draft and opens direct Notion editing', async ({ page }) => {
  await open(page)
  await page.getByRole('button', { name: 'New checkpoint', exact: true }).click()
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('A reviewed checkpoint draft')
  await page.getByRole('textbox', { name: 'What we observed', exact: true }).fill('The run did not produce a complete log.')
  await page.getByRole('textbox', { name: 'Scope and limits', exact: true }).fill('The hypothesis has not been tested successfully.')
  await page.getByRole('button', { name: 'Save draft to Notion' }).click()
  await expect(page.getByRole('dialog', { name: 'Review an exploration checkpoint' })).not.toBeVisible()
  const writes = (await calls(page, 'notion_tool')).filter((call: any) => call.args.tool === 'notion-create-pages')
  const record = writes.at(-1).args.arguments.pages[0]
  expect(record.properties.Status).toBe('Draft')
  expect(record.properties.Project).toEqual([(201).toString(16).padStart(32, '0')])
  expect(record.content).toContain('not verified evidence')
  await expect.poll(async () => (await calls(page, 'notion_layout')).at(-1).args.visible).toBe(true)
})

test('milestones are scoped outcomes with optional dates', async ({ page }) => {
  await open(page)
  await page.getByRole('navigation', { name: 'Project modules' }).getByRole('button', { name: 'Milestones', exact: true }).click()
  await page.getByRole('button', { name: 'Add milestone', exact: true }).click()
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Reproduce one result')
  await page.getByRole('textbox', { name: 'Outcome and evidence needed' }).fill('A reproducible command and verified artifact.')
  await page.getByRole('button', { name: 'Create in Notion', exact: true }).click()
  const writes = (await calls(page, 'notion_tool')).filter((call: any) => call.args.tool === 'notion-create-pages')
  expect(writes.at(-1).args.arguments.pages[0].properties).toMatchObject({ Name: 'Reproduce one result', Status: 'Planned' })
  expect(writes.at(-1).args.arguments.pages[0].properties).not.toHaveProperty('Year')
})

test('JSON imports reject another project and checkpoints persist as local drafts', async ({ page }) => {
  await open(page)
  await page.getByRole('button', { name: 'New checkpoint', exact: true }).click()
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('Keep my incomplete thinking')
  await page.getByRole('button', { name: 'Close research form' }).click()
  await page.getByRole('button', { name: 'New checkpoint', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Title', exact: true })).toHaveValue('Keep my incomplete thinking')
  await page.getByRole('dialog').getByText('Import checkpoint JSON', { exact: true }).click()
  await page.getByRole('textbox', { name: 'Checkpoint JSON' }).fill(JSON.stringify({ version: 1, id: 'wrong-project', project: `https://www.notion.so/${(202).toString(16).padStart(32, '0')}`, kind: 'Experiment' }))
  await page.getByRole('button', { name: 'Read JSON into the form' }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('does not match')
  expect((await calls(page, 'notion_tool')).some((call: any) => call.args.tool === 'notion-create-pages')).toBe(false)
})

test('project creation is explicit and research view fits a compact dark workspace', async ({ page }) => {
  await open(page, '&theme=linco-dark')
  await page.getByRole('button', { name: 'Back to all projects' }).click()
  await page.getByRole('button', { name: 'New project', exact: true }).last().click()
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('A third investigation')
  await page.getByRole('textbox', { name: 'Current question', exact: true }).fill('What should we investigate next?')
  await page.getByRole('button', { name: 'Create in Notion', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'A third investigation' })).toBeVisible()
  await page.setViewportSize({ width: 1000, height: 720 })
  const workspace = page.locator('.research-workspace')
  await expect(workspace).toBeVisible()
  expect(await workspace.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: 'artifacts/research-project-dark.png', animations: 'disabled' })
})
