import { expect, test } from '@playwright/test'

test.setTimeout(180000)
test.use({ deviceScaleFactor: 1, actionTimeout: 10000 })

test('browses offline themes, filters, favorites, and persists a selection', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/__index__', route => route.fulfill({ contentType: 'text/html', body: '<p>Preview</p>' }))
  await page.goto('/tests/browser/workbench.html?files&persist-theme')
  await expect(page.getByRole('button', { name: 'Settings', exact: true })).toBeVisible({ timeout: 120000 })
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const gallery = page.locator('.theme-gallery')
  const cards = gallery.locator('[data-theme-option]')
  const search = gallery.getByRole('searchbox')
  const filters = gallery.getByRole('group', { name: 'Filter themes' })
  await expect(cards).toHaveCount(32)
  await page.screenshot({ path: 'artifacts/theme-gallery-light.png' })
  await search.fill('rose')
  await expect(cards).toHaveCount(3)
  await filters.getByRole('button', { name: 'Light', exact: true }).click()
  await expect(cards).toHaveCount(1)
  await expect(cards).toHaveAttribute('data-theme-option', 'gallery-rose-pine-dawn')
  await filters.getByRole('button', { name: 'Dark', exact: true }).click()
  await expect(cards).toHaveCount(2)
  await search.fill('not-a-theme')
  await expect(cards).toHaveCount(0)
  await gallery.getByRole('button', { name: 'Show all themes' }).click()
  await expect(cards).toHaveCount(32)
  await search.fill('nord')
  const favorite = gallery.getByRole('checkbox', { name: 'Favorite Nord', exact: true })
  await favorite.focus()
  await page.keyboard.press('Space')
  await expect(favorite).toBeChecked()
  // Favoriting and searching do not silently change the active palette.
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'linco-light')
  await cards.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'gallery-nord')
  await gallery.getByRole('button', { name: 'Clear theme search' }).click()
  await filters.getByRole('button', { name: 'Favorites', exact: true }).click()
  await expect(cards).toHaveCount(1)
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'gallery-nord')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await filters.getByRole('button', { name: 'Favorites', exact: true }).click()
  await expect(cards).toHaveCount(1)
  await expect(favorite).toBeChecked()
  // Removing the last favorite immediately removes this checkbox from the DOM.
  await favorite.click()
  await expect(cards).toHaveCount(0)
  await gallery.getByRole('button', { name: 'Show all themes' }).click()
  await page.screenshot({ path: 'artifacts/theme-gallery-dark.png' })
  await page.setViewportSize({ width: 800, height: 720 })
  expect(await gallery.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  expect(errors).toEqual([])
})
