import { expect, test, type Page } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  // The native preview server serves project HTML, not the Vite app entry point.
  await page.route('**/__index__', (route) => route.fulfill({
    contentType: 'text/html',
    body: '<!doctype html><html lang="en"><head><title>Project preview</title></head><body style="font:14px system-ui;padding:40px;color:#293b31"><p style="font-size:11px;letter-spacing:2px;color:#627e6b">PROJECT PREVIEW</p><h1>Make something wonderful.</h1><p>Explore your project as you build it.</p><input aria-label="Preview draft" placeholder="Try your changes" style="padding:10px;border:1px solid #cad6ce;border-radius:6px;font:inherit"></body></html>',
  }))
})

async function openWorkbench(page: Page, query = '') {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto(`/tests/browser/workbench.html${query}`)
  await expect(page.getByRole('navigation', { name: 'Workspaces', exact: true })).toBeVisible({ timeout: 15000 })
  await expect(page.locator('.workspace-canvas')).toBeVisible()
  return errors
}

async function assertFits(page: Page) {
  const bounds = await page.evaluate(() => {
    const selectors = ['.workbench-content', '.workspace-canvas']
    return selectors.map((selector) => {
      const rect = document.querySelector(selector)!.getBoundingClientRect()
      return { selector, x: rect.x, right: rect.right, bottom: rect.bottom, width: rect.width, height: rect.height, viewport: [innerWidth, innerHeight] }
    })
  })
  for (const rect of bounds) {
    expect(rect.x, rect.selector).toBeGreaterThanOrEqual(0)
    expect(rect.right, rect.selector).toBeLessThanOrEqual(rect.viewport[0] + 1)
    expect(rect.bottom, rect.selector).toBeLessThanOrEqual(rect.viewport[1] + 1)
    expect(rect.height, rect.selector).toBeGreaterThan(40)
  }
}

test('three workspaces, themes, editor and settings preserve the running terminal', async ({ page }) => {
  const errors = await openWorkbench(page)
  await expect(page.locator('[data-terminal-kind="chat"] .xterm')).toBeVisible()
  const starts = () => page.evaluate(() => (window as any).__workbench.calls.filter((c: any) => c.cmd === 'term_start').length)
  const started = await starts()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'linco-light')
  await expect(page.getByRole('navigation', { name: 'Workspaces', exact: true }).getByRole('button')).toHaveCount(3)
  await expect(page.getByRole('button', { name: 'Vibe Working', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.locator('.workspace-drawer')).toHaveCount(0)
  await page.frameLocator('iframe').getByRole('textbox', { name: 'Preview draft' }).fill('Preview state stays here')
  await assertFits(page)
  await page.screenshot({ path: 'artifacts/design-light.png' })

  await page.getByRole('button', { name: 'Projects', exact: true }).click()
  await page.getByRole('button', { name: 'Switch to dark theme', exact: true }).click()
  await page.getByRole('button', { name: 'Close projects', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'linco-dark')
  await page.screenshot({ path: 'artifacts/design-dark.png' })
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await expect(page.locator('#agent-composer')).toBeHidden()
  await page.getByText('Welcome.tsx', { exact: true }).click()
  await expect(page.locator('.cm-editor').filter({ visible: true })).toBeVisible()
  await expect(page.locator('.cm-editor').filter({ visible: true })).toHaveCSS('background-color', 'rgb(28, 29, 31)')
  await page.screenshot({ path: 'artifacts/design-editor.png' })
  await page.locator('.cm-content').click()
  await page.keyboard.press('Control+End')
  await page.keyboard.press('Enter')
  await page.keyboard.type('// unsaved draft')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'VS Code Dark Modern', exact: false }).click()
  await page.locator('.settings-sidebar').getByRole('button').first().click()
  await expect(page.locator('.cm-editor').filter({ visible: true })).toHaveCSS('background-color', 'rgb(31, 31, 31)')
  await expect(page.locator('.cm-content')).toContainText('// unsaved draft')
  await page.getByRole('button', { name: 'Projects', exact: true }).click()
  await expect(page.locator('.workspace-drawer .sidebar-history')).toBeVisible()
  await page.getByRole('button', { name: 'Close projects', exact: true }).click()

  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Linco · Light', exact: false }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'linco-light')
  await page.screenshot({ path: 'artifacts/design-settings.png' })
  await page.locator('.settings-sidebar').getByRole('button').first().click()
  await expect(page.locator('.cm-editor').filter({ visible: true })).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await page.getByRole('button', { name: 'Vibe Working', exact: true }).click()
  await expect(page.locator('[data-terminal-kind="chat"] .xterm')).toBeVisible()
  await expect(page.frameLocator('iframe').getByRole('textbox', { name: 'Preview draft' })).toHaveValue('Preview state stays here')
  expect(await starts()).toBe(started)
  expect(errors).toEqual([])
})

test('commands work with keyboard, empty searches, Escape and focus restoration', async ({ page }) => {
  const errors = await openWorkbench(page)
  const input = page.locator('#agent-composer')
  await input.focus()
  await page.keyboard.press('Control+Shift+P')
  const search = page.getByRole('combobox')
  await expect(search).toBeFocused()
  await search.fill('no-such-command')
  await expect(page.getByText('No matching commands.', { exact: false })).toBeVisible()
  await search.fill('files')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Code', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.getByRole('button', { name: 'Vibe Working', exact: true }).click()
  await input.focus()
  await page.keyboard.press('Control+Shift+P')
  await search.fill('theme')
  await page.screenshot({ path: 'artifacts/design-commands.png' })
  await page.keyboard.press('Escape')
  await expect(input).toBeFocused()
  expect(errors).toEqual([])
})

test('first project onboarding opens a real project action and enables the composer', async ({ page }) => {
  const errors = await openWorkbench(page, '?empty')
  await expect(page.getByRole('heading', { name: 'Open a project' })).toBeVisible()
  await expect(page.locator('#agent-composer')).toBeHidden()
  await page.screenshot({ path: 'artifacts/design-welcome.png' })
  await page.locator('.welcome-view').getByRole('button', { name: 'Open project', exact: true }).click()
  await expect(page.locator('#agent-composer')).toBeEnabled()
  await expect(page.locator('.project-trigger')).toContainText('website')
  await page.locator('#agent-composer').fill('Build a welcome page')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page.locator('#agent-composer')).toHaveValue('')
  await expect.poll(() => page.evaluate(() => (window as any).__workbench.calls.some((c: any) => c.cmd === 'term_write' && c.args.data === '\r'))).toBe(true)
  expect(errors).toEqual([])
})

test('compact windows reserve full height for the preview and editor', async ({ page }) => {
  await page.setViewportSize({ width: 900, height: 600 })
  const errors = await openWorkbench(page)
  await expect(page.locator('.workspace-drawer')).toHaveCount(0)
  await assertFits(page)
  const width = await page.locator('.workbench-content').evaluate((node) => node.getBoundingClientRect().width)
  expect(width).toBe(900)
  await expect(page.getByRole('navigation', { name: 'Open sessions', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Projects', exact: true }).click()
  await expect(page.locator('.workspace-drawer .sidebar-history')).toBeVisible()
  await page.getByRole('button', { name: 'Close projects', exact: true }).click()
  await assertFits(page)
  await page.screenshot({ path: 'artifacts/design-compact.png' })
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await page.getByRole('navigation', { name: 'Workspace tools' }).getByRole('button', { name: 'Terminal', exact: true }).click()
  await assertFits(page)
  expect(errors).toEqual([])
})

test('Chinese navigation and dark onboarding fit the workspace', async ({ page }) => {
  await page.goto('/tests/browser/workbench.html?empty&lang=zh&theme=linco-dark')
  await expect(page.getByRole('heading', { name: '打开项目' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: '工作空间', exact: true })).toBeVisible()
  await assertFits(page)
  await page.screenshot({ path: 'artifacts/design-chinese.png' })
})

test('Visual opens the canvas, Code remembers its tool, and the composer stays uncluttered', async ({ page }) => {
  const errors = await openWorkbench(page)
  await expect(page.locator('#agent-composer')).toBeVisible()
  const preview = await page.locator('[data-workspace-view="preview"]').boundingBox()
  const composer = await page.locator('.pane-composer').boundingBox()
  expect(preview!.y + preview!.height).toBeGreaterThanOrEqual(composer!.y + composer!.height - 1)
  expect(preview!.x).toBeGreaterThanOrEqual(composer!.x + composer!.width)

  await expect(page.locator('.agent-composer').getByRole('button')).toHaveCount(2)
  await expect(page.getByRole('button', { name: 'Agent options', exact: true })).toHaveCount(0)
  await expect(page.locator('.composer-toolbar')).toHaveCount(0)

  await page.getByRole('button', { name: 'Visual', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Canvas', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.locator('[data-workspace-view="drawing"]')).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Open sessions', exact: true })).toHaveCount(0)
  await page.screenshot({ path: 'artifacts/design-visual.png' })
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await page.getByRole('navigation', { name: 'Workspace tools' }).getByRole('button', { name: 'Git', exact: true }).click()
  await page.getByRole('button', { name: 'Vibe Working', exact: true }).click()
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await expect(page.getByRole('navigation', { name: 'Workspace tools' }).getByRole('button', { name: 'Git', exact: true })).toHaveAttribute('aria-current', 'page')
  expect(errors).toEqual([])
})

test('interface typography follows saved sizes without zooming the editor or preview', async ({ page }) => {
  const errors = await openWorkbench(page)
  const mode = page.getByRole('button', { name: 'Vibe Working', exact: true })
  await expect(mode).toHaveCSS('font-size', '12px')
  await expect(page.locator('#agent-composer')).toHaveCSS('font-size', '12px')
  await expect(page.locator('.workbench-titlebar')).toHaveCSS('height', '40px')
  const starts = await page.evaluate(() => (window as any).__workbench.calls.filter((c: any) => c.cmd === 'term_start').length)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const size = page.getByRole('slider')
  await size.fill('11')
  await expect(mode).toHaveCSS('font-size', '11px')
  await expect(page.locator('.settings-sidebar nav button').first()).toHaveCSS('font-size', '11px')
  await expect.poll(() => page.evaluate(() => (window as any).__workbench.getConfig().ui_font_size)).toBe(11)
  await size.fill('16')
  await expect(mode).toHaveCSS('font-size', '16px')
  await page.locator('.settings-sidebar').getByRole('button').first().click()
  await expect(page.locator('#agent-composer')).toHaveCSS('font-size', '16px')
  await expect(page.frameLocator('iframe').locator('body')).toHaveCSS('font-size', '14px')
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await page.getByText('Welcome.tsx', { exact: true }).click()
  await expect(page.locator('.cm-editor').filter({ visible: true })).toHaveCSS('font-size', '13px')
  expect(await page.evaluate(() => (window as any).__workbench.calls.filter((c: any) => c.cmd === 'term_start').length)).toBe(starts)
  expect(errors).toEqual([])
})

test('cold-start terminal sizing waits for the bundled monospace face', async ({ page }) => {
  await page.route('**/JetBrainsMono-Variable.woff2*', async (route) => {
    await new Promise((resolve) => setTimeout(resolve, 400))
    await route.continue()
  })
  const errors = await openWorkbench(page)
  const terminal = page.locator('[data-terminal-kind="chat"]')
  await expect(terminal.locator('.xterm-screen')).toBeVisible()
  expect(await page.evaluate(() => document.fonts.check('13.5px "JetBrains Mono"'))).toBe(true)
  const metrics = await terminal.evaluate((host) => {
    const style = getComputedStyle(host.querySelector('.xterm')!)
    const available = host.clientWidth - parseFloat(style.paddingLeft) - parseFloat(style.paddingRight)
    return { available, rendered: host.querySelector('.xterm-screen')!.getBoundingClientRect().width }
  })
  expect(metrics.rendered).toBeGreaterThan(metrics.available - 25)
  expect(metrics.rendered).toBeLessThanOrEqual(metrics.available + 1)
  expect(errors).toEqual([])
})

test('open sessions are in the top strip while history remains in Projects', async ({ page }) => {
  const errors = await openWorkbench(page)
  const rail = page.getByRole('navigation', { name: 'Open sessions', exact: true })
  await expect(rail).toBeVisible()
  await expect(page.locator('.workspace-sessions')).toHaveCount(0)
  await expect(page.locator('.sidebar-history')).toHaveCount(0)
  await page.locator('#agent-composer').fill('Draft for linco')
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await expect(rail).toBeVisible()
  await page.getByRole('button', { name: 'Projects', exact: true }).click()
  await expect(page.locator('.sidebar-history').getByRole('button', { name: /Build the project workspace/ })).toBeVisible()
  await expect(page.locator('.workspace-drawer .session-rail')).toHaveCount(0)
  await page.locator('.workspace-drawer').getByRole('button', { name: 'website', exact: true }).click()
  await expect(rail.getByRole('button')).toHaveCount(2)
  await rail.getByRole('button', { name: /^website,/ }).click()
  await page.locator('#agent-composer').fill('Draft for website')
  const starts = await page.evaluate(() => (window as any).__workbench.calls.filter((call: any) => call.cmd === 'term_start').length)
  await rail.getByRole('button', { name: /^linco,/ }).click()
  await expect(page.getByRole('button', { name: 'Code', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.locator('#agent-composer')).toHaveValue('Draft for linco')
  await page.locator('#agent-composer').press('End')
  await page.locator('#agent-composer').press('!')
  expect(await page.evaluate(() => (window as any).__workbench.calls.filter((call: any) => call.cmd === 'term_write').at(-1).args.data)).toBe('!')
  await rail.getByRole('button', { name: /^website,/ }).click()
  await expect(page.locator('#agent-composer')).toHaveValue('Draft for website')
  expect(await page.evaluate(() => (window as any).__workbench.calls.filter((call: any) => call.cmd === 'term_start').length)).toBe(starts)
  expect(await page.evaluate(() => (window as any).__workbench.calls.filter((call: any) => call.cmd === 'term_kill'))).toEqual([])
  await page.screenshot({ path: 'artifacts/sessions-top-strip.png' })
  expect(errors).toEqual([])
})

test('history resume explains the restart and cancel does not interrupt an agent', async ({ page }) => {
  await openWorkbench(page)
  await page.locator('#agent-composer').fill('Keep this draft until I resume')
  const starts = () => page.evaluate(() => (window as any).__workbench.calls.filter((call: any) => call.cmd === 'term_start').length)
  const before = await starts()
  await page.getByRole('button', { name: 'Projects', exact: true }).click()
  const history = page.locator('.sidebar-history')
  await history.getByRole('button', { name: /Build the project workspace/ }).click()
  await expect(history.getByText('This restarts the agent', { exact: false })).toBeVisible()
  await history.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(await starts()).toBe(before)
  await history.getByRole('button', { name: /Build the project workspace/ }).click()
  await history.getByRole('button', { name: 'Resume conversation', exact: true }).click()
  await expect.poll(starts).toBe(before + 1)
  await expect(page.locator('.workspace-drawer')).toHaveCount(0)
  await expect(page.locator('#agent-composer')).toHaveValue('')
})

test('the message box grows, scrolls long drafts, and leaves room for the terminal', async ({ page }) => {
  await page.setViewportSize({ width: 1000, height: 650 })
  const errors = await openWorkbench(page)
  const input = page.locator('#agent-composer')
  const initial = (await input.boundingBox())!.height
  expect(initial).toBeGreaterThanOrEqual(104)
  await page.getByRole('separator', { name: 'Resize message box', exact: true }).press('ArrowUp')
  expect((await input.boundingBox())!.height).toBeGreaterThan(initial)
  const draft = Array.from({ length: 30 }, (_, i) => `Research step ${i + 1}: keep this entire line.`).join('\n')
  await input.fill(draft)
  await expect(input).toHaveValue(draft)
  await expect(input).toHaveCSS('overflow-y', 'auto')
  expect((await input.boundingBox())!.height).toBeGreaterThan(initial + 40)
  const terminal = await page.locator('[data-terminal-kind="chat"]:visible').boundingBox()
  const composer = await page.locator('.pane-composer').boundingBox()
  expect(terminal!.y + terminal!.height).toBeLessThanOrEqual(composer!.y)
  expect(terminal!.height).toBeGreaterThan(200)
  await input.dispatchEvent('keydown', { key: 'Enter', isComposing: true })
  await expect(input).toHaveValue(draft)
  await input.press('ArrowUp')
  await expect(input).toHaveValue(draft)
  await page.screenshot({ path: 'artifacts/composer-expanded.png' })
  expect(errors).toEqual([])
})

for (const state of ['empty', 'error']) {
  test(`local history keeps a refresh action when ${state}`, async ({ page }) => {
    await openWorkbench(page, `?history-${state}`)
    await page.getByRole('button', { name: 'Projects', exact: true }).click()
    await expect(page.locator('.sidebar-history')).toBeVisible()
    await expect(page.locator('.sidebar-history').getByRole('button', { name: /refresh|retry/i }).first()).toBeVisible()
  })
}
