use std::collections::BTreeMap;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

use crate::{LogicalChannel, SessionKind, SessionState};

pub const FILE_LIST_DEFAULT_LIMIT: u16 = 100;
pub const FILE_LIST_MAX_LIMIT: u16 = 256;

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct EmptyParams {}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct SystemInfoResponse {
    pub name: String,
    pub version: String,
    pub protocol_version: u8,
    pub server_epoch: Uuid,
    pub platform: String,
    pub architecture: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct WorkspaceSummary {
    pub id: Uuid,
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct WorkspaceListResponse {
    pub workspaces: Vec<WorkspaceSummary>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct SessionStartRequest {
    pub workspace_id: Uuid,
    /// Generated by the client before the call so an ambiguous result can be reconciled safely.
    pub session_id: Uuid,
    pub kind: SessionKind,
    #[serde(default = "default_cwd")]
    pub cwd: String,
    #[serde(default = "default_rows")]
    pub rows: u16,
    #[serde(default = "default_columns")]
    pub columns: u16,
    #[serde(default)]
    pub pixel_width: u16,
    #[serde(default)]
    pub pixel_height: u16,
    #[serde(default)]
    pub environment: BTreeMap<String, String>,
    #[serde(default)]
    pub agent_arguments: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct SessionSummary {
    pub id: Uuid,
    pub stream_id: u32,
    pub generation: u64,
    pub title: String,
    pub workspace_name: String,
    pub kind: SessionKind,
    pub state: SessionState,
    /// Unix epoch milliseconds.
    pub updated_at: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct SessionListResponse {
    pub sessions: Vec<SessionSummary>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct SessionGenerationRequest {
    pub session_id: Uuid,
    pub generation: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct SessionStopResponse {
    pub stopped: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct TerminalResizeRequest {
    pub session_id: Uuid,
    pub generation: u64,
    pub rows: u16,
    pub columns: u16,
    #[serde(default)]
    pub pixel_width: u16,
    #[serde(default)]
    pub pixel_height: u16,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct TerminalResizeResponse {
    pub resized: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct TerminalCursorRequest {
    pub stream_id: u32,
    pub generation: u64,
    #[serde(default)]
    pub offset: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct TerminalDetachRequest {
    pub stream_id: u32,
    pub generation: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct TerminalDetachResponse {
    pub detached: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct SessionResumeResponse {
    pub stream_id: u32,
    pub generation: u64,
    pub starting_offset: u64,
    /// Server-authoritative next byte offset for terminal input on this generation.
    pub input_through: u64,
    pub lane: LogicalChannel,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct WorkspacePathRequest {
    pub workspace_id: Uuid,
    pub path: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct FileListRequest {
    pub workspace_id: Uuid,
    #[serde(default)]
    pub path: String,
    /// Opaque continuation token returned by the previous page.
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default = "default_file_list_limit")]
    pub limit: u16,
}

impl FileListRequest {
    pub fn validate(&self) -> Result<(), DtoValidationError> {
        if !(1..=FILE_LIST_MAX_LIMIT).contains(&self.limit) {
            return Err(DtoValidationError::FileListLimit {
                actual: self.limit,
                max: FILE_LIST_MAX_LIMIT,
            });
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum FileKind {
    Directory,
    File,
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct FileEntry {
    pub name: String,
    pub path: String,
    pub kind: FileKind,
    pub size: Option<u64>,
    pub modified_at: Option<u64>,
    pub etag: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct FileListResponse {
    pub path: String,
    pub entries: Vec<FileEntry>,
    /// Opaque token for the next page; absent when the listing is complete.
    pub next_cursor: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub enum HttpAuthorizationScheme {
    #[serde(rename = "LincoCapability")]
    LincoCapability,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub enum HttpUploadMethod {
    #[serde(rename = "PUT")]
    Put,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct FileReadResponse {
    pub url: String,
    pub authorization_scheme: HttpAuthorizationScheme,
    pub capability: String,
    pub expires_in_ms: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct FileWriteRequest {
    pub workspace_id: Uuid,
    pub path: String,
    pub content_length: u64,
    pub expected_revision: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct FileWriteResponse {
    pub url: String,
    pub method: HttpUploadMethod,
    pub authorization_scheme: HttpAuthorizationScheme,
    pub capability: String,
    pub if_match: String,
    pub content_length: u64,
    pub max_bytes: u64,
    pub expires_in_ms: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct PreviewResolveResponse {
    pub bootstrap_url: String,
    pub authorization_scheme: HttpAuthorizationScheme,
    pub capability: String,
    pub expires_in_ms: u64,
}

#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum DtoValidationError {
    #[error("file list limit {actual} is outside 1..={max}")]
    FileListLimit { actual: u16, max: u16 },
}

fn default_cwd() -> String {
    ".".into()
}

const fn default_rows() -> u16 {
    24
}

const fn default_columns() -> u16 {
    80
}

const fn default_file_list_limit() -> u16 {
    FILE_LIST_DEFAULT_LIMIT
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde::{de::DeserializeOwned, Serialize};
    use serde_json::Value;

    use crate::{Permission, RpcMethod};

    #[test]
    fn file_list_defaults_are_bounded_for_control_frames() {
        let request: FileListRequest = serde_json::from_value(serde_json::json!({
            "workspace_id": "00112233-4455-6677-8899-aabbccddeeff"
        }))
        .unwrap();
        assert_eq!(request.path, "");
        assert_eq!(request.limit, FILE_LIST_DEFAULT_LIMIT);
        assert_eq!(request.cursor, None);
        request.validate().unwrap();
    }

    #[test]
    fn file_list_rejects_unbounded_page_sizes() {
        let request = FileListRequest {
            workspace_id: Uuid::nil(),
            path: String::new(),
            cursor: None,
            limit: FILE_LIST_MAX_LIMIT + 1,
        };
        assert!(matches!(
            request.validate(),
            Err(DtoValidationError::FileListLimit { .. })
        ));
    }

    #[test]
    fn request_dtos_reject_misspelled_fields() {
        let value = serde_json::json!({
            "workspace_id": "00112233-4455-6677-8899-aabbccddeeff",
            "path": "README.md",
            "content_length": 4,
            "expected_etag": "wrong-field"
        });
        assert!(serde_json::from_value::<FileWriteRequest>(value).is_err());
    }

    #[test]
    fn capability_literals_have_one_canonical_spelling() {
        assert_eq!(
            serde_json::to_string(&HttpAuthorizationScheme::LincoCapability).unwrap(),
            "\"LincoCapability\""
        );
        assert_eq!(
            serde_json::to_string(&HttpUploadMethod::Put).unwrap(),
            "\"PUT\""
        );
    }

    #[test]
    fn shared_fixture_covers_every_v1_rpc_with_typed_dtos() {
        let fixture: Value =
            serde_json::from_str(include_str!("../fixtures/v1-conformance.json")).unwrap();
        let cases = fixture["rpc_contract_cases"].as_array().unwrap();
        assert_eq!(cases.len(), 12);

        let mut methods = Vec::new();
        for case in cases {
            let method: RpcMethod =
                serde_json::from_value(Value::String(case["method"].as_str().unwrap().into()))
                    .unwrap();
            let permission: Permission =
                serde_json::from_value(Value::String(case["permission"].as_str().unwrap().into()))
                    .unwrap();
            let policy = method.policy();
            assert_eq!(policy.permission, permission);
            assert_eq!(policy.mutating, case["mutating"].as_bool().unwrap());
            assert_eq!(policy.requires_idempotency_key, policy.mutating);

            match method {
                RpcMethod::SystemInfo => {
                    assert_round_trip::<EmptyParams>(&case["request"]);
                    assert_round_trip::<SystemInfoResponse>(&case["response"]);
                }
                RpcMethod::WorkspaceList => {
                    assert_round_trip::<EmptyParams>(&case["request"]);
                    assert_round_trip::<WorkspaceListResponse>(&case["response"]);
                }
                RpcMethod::SessionList => {
                    assert_round_trip::<EmptyParams>(&case["request"]);
                    assert_round_trip::<SessionListResponse>(&case["response"]);
                }
                RpcMethod::SessionStart => {
                    assert_round_trip::<SessionStartRequest>(&case["request"]);
                    assert_round_trip::<SessionSummary>(&case["response"]);
                }
                RpcMethod::SessionStop => {
                    assert_round_trip::<SessionGenerationRequest>(&case["request"]);
                    assert_round_trip::<SessionStopResponse>(&case["response"]);
                }
                RpcMethod::SessionResume => {
                    assert_round_trip::<TerminalCursorRequest>(&case["request"]);
                    assert_round_trip::<SessionResumeResponse>(&case["response"]);
                }
                RpcMethod::TerminalDetach => {
                    assert_round_trip::<TerminalDetachRequest>(&case["request"]);
                    assert_round_trip::<TerminalDetachResponse>(&case["response"]);
                }
                RpcMethod::TerminalResize => {
                    assert_round_trip::<TerminalResizeRequest>(&case["request"]);
                    assert_round_trip::<TerminalResizeResponse>(&case["response"]);
                }
                RpcMethod::FileList => {
                    let request: FileListRequest = decode(case["request"].clone());
                    request.validate().unwrap();
                    assert_eq!(serde_json::to_value(request).unwrap(), case["request"]);
                    assert_round_trip::<FileListResponse>(&case["response"]);
                }
                RpcMethod::FileRead => {
                    assert_round_trip::<WorkspacePathRequest>(&case["request"]);
                    assert_round_trip::<FileReadResponse>(&case["response"]);
                }
                RpcMethod::FileWrite => {
                    assert_round_trip::<FileWriteRequest>(&case["request"]);
                    assert_round_trip::<FileWriteResponse>(&case["response"]);
                }
                RpcMethod::PreviewResolve => {
                    assert_round_trip::<WorkspacePathRequest>(&case["request"]);
                    assert_round_trip::<PreviewResolveResponse>(&case["response"]);
                }
            }
            methods.push(method);
        }

        methods.sort();
        methods.dedup();
        let mut expected = vec![
            RpcMethod::SystemInfo,
            RpcMethod::WorkspaceList,
            RpcMethod::SessionList,
            RpcMethod::SessionStart,
            RpcMethod::SessionStop,
            RpcMethod::SessionResume,
            RpcMethod::TerminalDetach,
            RpcMethod::TerminalResize,
            RpcMethod::FileList,
            RpcMethod::FileRead,
            RpcMethod::FileWrite,
            RpcMethod::PreviewResolve,
        ];
        expected.sort();
        assert_eq!(methods, expected);
    }

    #[test]
    fn generated_schema_contains_high_risk_wire_fields() {
        let file_write = serde_json::to_string(&schemars::schema_for!(FileWriteRequest)).unwrap();
        assert!(file_write.contains("content_length"));
        assert!(file_write.contains("expected_revision"));
        assert!(!file_write.contains("expected_etag"));

        let file_list = serde_json::to_string(&schemars::schema_for!(FileListResponse)).unwrap();
        assert!(file_list.contains("next_cursor"));

        let session = serde_json::to_string(&schemars::schema_for!(SessionSummary)).unwrap();
        for field in ["stream_id", "generation", "workspace_name", "updated_at"] {
            assert!(session.contains(field), "missing {field}");
        }

        let capability = serde_json::to_string(&schemars::schema_for!(FileWriteResponse)).unwrap();
        for field in [
            "authorization_scheme",
            "capability",
            "if_match",
            "max_bytes",
        ] {
            assert!(capability.contains(field), "missing {field}");
        }
    }

    fn assert_round_trip<T>(value: &Value)
    where
        T: DeserializeOwned + Serialize,
    {
        let decoded: T = decode(value.clone());
        assert_eq!(serde_json::to_value(decoded).unwrap(), *value);
    }

    fn decode<T: DeserializeOwned>(value: Value) -> T {
        serde_json::from_value(value).unwrap()
    }
}
