import { expect, test } from '@playwright/test'

test('public file browser opens real per-file samples and preserves separate drafts', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  const editor = page.locator('[data-workspace-view="files"] .cm-content[contenteditable="true"]:visible')
  await page.locator('[data-file-entry="README.md"]').click()
  await expect(editor).toContainText('# Pocket Garden')
  await page.locator('[data-file-entry="package.json"]').click()
  await expect(editor).toContainText('pocket-garden-demo')
  await page.locator('[data-file-entry="index.html"]').click()
  await expect(editor).toContainText('<!doctype html>')
  await page.locator('[data-file-entry="scripts"]').click()
  await page.locator('[data-file-entry="evaluate.py"]').click()
  await expect(editor).toContainText('import csv')
  await page.locator('[data-file-entry="README.md"]').click()
  await editor.click()
  await page.keyboard.press('Control+End')
  await page.keyboard.insertText('\nMy garden notes.\n')
  await page.keyboard.press('Control+s')
  await expect(page.locator('.demo-notice')).toContainText('source examples are not compiled')
  await page.locator('[data-file-entry="package.json"]').click()
  await expect(editor).not.toContainText('My garden notes.')
  await page.locator('[data-file-entry="README.md"]').click()
  await expect(editor).toContainText('My garden notes.')
  await page.reload()
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await page.locator('[data-file-entry="README.md"]').click()
  await expect(editor).not.toContainText('My garden notes.')
})

test('shadow diff shows only the latest turn while Git keeps earlier changes', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Add a sunflower', exact: false }).click()
  await page.locator('#agent-composer').press('Enter')
  await expect(page.getByRole('button', { name: 'Water Sunflower', exact: true })).toBeVisible()
  await page.locator('.demo-turn-review summary').click()
  const review = page.getByRole('region', { name: 'This-turn diff for src/garden.json' })
  await expect(review.locator('.bg-diff-added')).toContainText(['Lavender', 'Sunflower'])
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await page.locator('[data-file-entry="src"]').click()
  await page.locator('[data-file-entry="garden.json"]').click()
  const files = page.locator('[data-workspace-view="files"]')
  await expect(files.locator('.bg-diff-added')).toContainText(['Lavender', 'Sunflower'])
  await page.locator('.demo-shell').screenshot({ path: 'docs/images/turn-review.png', animations: 'disabled' })
  await files.getByRole('button', { name: 'File', exact: true }).click()
  await expect(files.locator('.cm-content:visible')).toContainText('Sunflower')
  await page.getByRole('button', { name: 'Vibe Working', exact: true }).click()
  await page.getByRole('button', { name: 'Make it midnight', exact: false }).click()
  await page.locator('#agent-composer').press('Enter')
  await expect(page.locator('.garden-preview')).toHaveClass(/garden-night/)
  await expect(review.locator('.bg-diff-added')).toContainText(['"night": true'])
  await expect(review.locator('.bg-diff-added')).not.toContainText(['Sunflower'])
  await page.locator('#agent-composer').fill('Explain this project')
  await page.locator('#agent-composer').press('Enter')
  await expect(page.locator('.demo-turn-review summary')).toContainText('0 changed files')
  await expect(page.getByRole('button', { name: 'Water Sunflower', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await page.getByRole('navigation', { name: 'Workspace tools' }).getByRole('button', { name: 'Git', exact: true }).click()
  await expect(page.locator('[data-workspace-view="git"]')).toContainText('garden.json')
})
