import { expect, test } from '@playwright/test'

test('the real workspace supports a playable garden and a clearly scripted agent change', async ({ page, baseURL }) => {
  const errors: string[] = []
  const outside: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (/^https?:/.test(request.url()) && new URL(request.url()).origin !== new URL(baseURL!).origin) outside.push(request.url()) })
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Water Basil', exact: true })).toBeVisible({ timeout: 120000 })
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: 'Water Basil', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Water Basil', exact: true })).toContainText('In bloom!')
  await page.getByRole('button', { name: 'Add a sunflower', exact: false }).click()
  await expect(page.locator('#agent-composer')).toHaveValue('Add a sunflower')
  await page.locator('#agent-composer').press('Enter')
  await expect(page.getByRole('button', { name: 'Water Sunflower', exact: true })).toBeVisible()
  await expect(page.locator('.demo-notice')).toContainText('No AI model was called')
  await page.getByRole('button', { name: 'Make it midnight', exact: false }).click()
  await page.locator('#agent-composer').press('Enter')
  await expect(page.locator('.garden-preview')).toHaveClass(/garden-night/)
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download garden.json', exact: false }).click()
  expect((await downloaded).suggestedFilename()).toBe('garden.json')
  expect(errors).toEqual([])
  expect(outside).toEqual([])
})

test('edit sample data, save and see the result without touching the desktop backend', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Code', exact: true })).toBeVisible({ timeout: 120000 })
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await page.locator('[data-file-entry="src"]').click()
  await page.locator('[data-file-entry="garden.json"]').click()
  const editor = page.locator('.cm-content').filter({ visible: true })
  await expect(editor).toContainText('A little room to grow.')
  await editor.click()
  await page.keyboard.press('Control+A')
  await page.keyboard.insertText('{ invalid JSON')
  await page.keyboard.press('Control+s')
  await expect(page.locator('.demo-notice')).toContainText('JSON is invalid')
  await expect(editor).toBeVisible()
  await editor.click()
  await page.keyboard.press('Control+A')
  await page.keyboard.insertText(JSON.stringify({ title: 'My first little app.', night: false, plants: ['Basil', 'Fern'] }, null, 2))
  await page.keyboard.press('Control+s')
  await expect(page.locator('.demo-notice')).toContainText('Saved to demo memory')
  await page.getByRole('button', { name: 'Vibe Working', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'My first little app.' })).toBeVisible()
  await page.getByRole('button', { name: 'Water Fern', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'A little room to grow.' })).toBeVisible()
})

test('capture the real demo and explore project memory, logs and themes', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Water Basil', exact: true })).toBeVisible({ timeout: 120000 })
  await expect(page.locator('[data-terminal-kind="chat"] .xterm-screen')).toBeVisible()
  await page.waitForTimeout(500)
  await page.locator('.demo-shell').screenshot({ path: 'docs/images/workbench.png', animations: 'disabled' })
  await page.setViewportSize({ width: 1200, height: 630 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: 'demo/public/social-preview.png', animations: 'disabled' })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Notes', exact: true }).click()
  await page.getByRole('button', { name: /Memory study.*Can a new agent/ }).click()
  await page.getByRole('navigation', { name: 'Project modules' }).getByRole('button', { name: 'Milestones', exact: true }).click()
  await expect(page.getByRole('button', { name: /Reproduce the baseline/ })).toBeVisible()
  await page.locator('.demo-shell').screenshot({ path: 'docs/images/project-memory.png', animations: 'disabled' })
  await page.getByRole('button', { name: 'Code', exact: true }).click()
  await page.getByRole('navigation', { name: 'Workspace tools' }).getByRole('button', { name: /^Terminal/ }).click()
  await expect(page.locator('.log-reader:visible')).toContainText('loss: 0.194')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.locator('[data-theme-option="gallery-nord"]').click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'gallery-nord')
  await page.locator('.demo-shell').screenshot({ path: 'docs/images/themes.png', animations: 'disabled' })
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'gallery-nord')
})

test('mobile navigation and static search content remain available', async ({ page, browser, baseURL }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(391)
  const context = await browser.newContext({ javaScriptEnabled: false })
  const staticPage = await context.newPage()
  await staticPage.goto(baseURL!)
  await expect(staticPage.getByRole('heading', { level: 1 })).toContainText('Keep the vibe.')
  await expect(staticPage.getByRole('heading', { name: 'A landing page for your side project' })).toBeVisible()
  expect(await staticPage.locator('script[type="application/ld+json"]').textContent()).toContain('SoftwareApplication')
  await context.close()
})
